name: Send Weekly Update Email

on:
  schedule:
    - cron: '0 17 * * 5'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send email
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
        DEV_RELEASES_DB: ${{ secrets.DEV_RELEASES_DB }}
        DEVELOPMENT_TASKS_DB: ${{ secrets.DEVELOPMENT_TASKS_DB }}
      run: python main.py
